### ISSUE TITLE
Problème import

### ISSUE THREAD

**Issue by bi-ayefo** [rodrigueaf/janusgs#1]
Quand j'ai tenté l'import en masse, ça n'a pas marché.

- [ ] @rodrigueaf peux-tu tester et me revenir stp?
- [ ] Prévoir la mise à jour les spécifications et les tests

**Comment by bi-ayefo** [comment]
Message d'erreur
![erreur import](https://user-images.githubusercontent.com/8646786/44293152-f1204800-a278-11e8-9ab1-0e62a856415b.png)

Données de test
[DonneesTestImportJournal.txt](https://github.com/rodrigueaf/janusgs/files/2299004/DonneesTestImportJournal.txt)

**Comment by rodrigueaf** [comment]
Problème résolu
