### ISSUE TITLE
Journal datagrid / Conflit défilement page et datagrid

### ISSUE THREAD

**Issue by bi-ayefo** [rodrigueaf/janusgs#12]
Difficile de gérer 2 barres de défilement en même temps. Choisir une et laisser l'autre.

**Comment by rodrigueaf** [comment]
Corrigé

J'ai réduit la taille du tableau pour faire disparaître la barre de défilement de la page.
L'inverse aussi était possible. c'est à dire augmenter la taille du tableau pour faire disparaître la barre de défilement de ce dernier. Mais quand je l'ai fais, le tableau est devenu lent.

Le composant ui-grid n'a pas cette fonctionnalité par défaut.
