### ISSUE TITLE
Journal datagrid / Absence de filtres de recherche pour les champs de liste

### ISSUE THREAD

**Issue by bi-ayefo** [rodrigueaf/janusgs#13]
![image](https://user-images.githubusercontent.com/8646786/44677612-ee1a1a00-aa25-11e8-88ca-e3f7985567ce.png)

**Comment by rodrigueaf** [comment]
Le composant par de défaut qui fait office de liste de liste déroulante dans le composant ui-grid n'a pas cette fonctionnalité. L'ajout de cette fonctionnalité fait partie des amélioration et des erreurs à corriger

**Comment by rodrigueaf** [comment]
Résolu
