### ISSUE TITLE
Journal datagrid / Format heure début et heure fin dans la base de données

### ISSUE THREAD

**Issue by bi-ayefo** [rodrigueaf/janusgs#18]
Utiliser le format heure (hh:mm) plutôt que dateheure.

**Comment by rodrigueaf** [comment]
J'ai changer le format. Mais pour le tester, il faudra exécuter l'application sur une base vierge.
Si après le test ça te convient, je t'enverrai le script sql pour faire la migration de tes anciennes données

**Comment by bi-ayefo** [comment]
Ok.
