### ISSUE TITLE
Journal datagrid / Revoir la hauteur du grid

### ISSUE THREAD

**Issue by bi-ayefo** [rodrigueaf/janusgs#19]
La hauteur du grid n'est pas du tout ergonomique. A revoir en urgence.

**Comment by rodrigueaf** [comment]
J'ai diminué la taille du datagrid pour la raison expliquée ici https://github.com/rodrigueaf/janusgs/issues/12#issuecomment-416602151

Merci de confirmer si je dois augmenter à nouveau la taille tout en prenant en compte l'explication donnée

**Comment by bi-ayefo** [comment]
Peux-tu créer une branche où tu vas implémenter la version sans la barre de défilement dans le tableau pour que je teste la lenteur?

**Comment by rodrigueaf** [comment]
J'ai augmenté la hauteur de la grid. Pour une affichage de 50 lignes (config par défaut), tu n'aura pas le scroller du grid. Mais si tu augmente le nombre de lignes à afficher (150 ou 300), le scroller réapparaîtra.

**Comment by bi-ayefo** [comment]
Ok. Résolu.
