### ISSUE TITLE
Journal datagrid / Identifiants

### ISSUE THREAD

**Issue by bi-ayefo** [rodrigueaf/janusgs#20]
Il y a une incohérence dans le système de pagination. Les id étant ordonnés par ordre ascendant, la première ligne devrait être le 1er Août au lieu du 26 Août.

![image](https://user-images.githubusercontent.com/8646786/45288813-25370380-b4db-11e8-9841-16c0a810b606.png)

**Comment by rodrigueaf** [comment]
as tu des lignes enregistrées sur le 1er Août ?

**Comment by bi-ayefo** [comment]
Oui. Dans la base, les données vont du 01/08 au 10/09

**Comment by rodrigueaf** [comment]
Je n'ai pas pu reproduire cette erreur à mon niveau

**Comment by bi-ayefo** [comment]
Dans une base vide:
- Importer les lignes dans le journal en pièce jointe
- Vérifier les lignes de la première page. Si le nombre de lignes affichées est de 50, on doit avoir les 50 premières lignes du journal. Mais ce n'est pas le cas. La première page indique plutôt les 50 dernières lignes. Pas normal.

[Import400lignes.txt](https://github.com/rodrigueaf/janusgs/files/2489248/Import400lignes.txt)

**Comment by rodrigueaf** [comment]
Au fait la liste a été triée par ordre décroissante sur la date d'enregistrement de la ligne. c'est pour cela que ceux sont les 50 dernières enregistrement qui s'affichent. Veux-tu plutôt que ce soit trier par ordre croissante?

**Comment by bi-ayefo** [comment]
Oui je pense que c'est mieux. C'est plus facile à lire.

**Comment by rodrigueaf** [comment]
Corrigé. La liste est triée par ordre croissante sur la date d'enregistrement
