### ISSUE TITLE
Import : Retour à la ligne description ligne journal

### ISSUE THREAD

**Issue by bi-ayefo** [rodrigueaf/janusgs#22]
Il serait si tu on peut implémenter le retour à la ligne dans la description d'une ligne journal. Comme pour les fichiers csv, la description doit donc être entourée de "

Exemple de ligne journal avec retour à la ligne

15/10/2018;15:10;16:20;"Tests JanusGS
- Récupération code source
- Compilation et déploiement avec une base de test
- Test formatage heure début et heure fin"

Lorsque le texte contient un ", alors le " doit être doublé comme cela est aussi le cas pour les fichiers csv.

Exemple

15/10/2018;15:10;16:20;"Tests projet ""JanusGS""
- Récupération code source
- Compilation et déploiement avec une base de test
- Test formatage heure début et heure fin"

**Comment by rodrigueaf** [comment]
Resolu
