### ISSUE TITLE
Régression : Les numéros de lignes dans la zone d'import ne correspondent plus aux numéros de lignes dans un éditeur de texte comme Notepad

### ISSUE THREAD

**Issue by bi-ayefo** [rodrigueaf/janusgs#24]
C'était le cas avant l'implémentation de la nouvelle fonctionnalité de gestion des retours à la ligne.
Voir issue #22

**Comment by rodrigueaf** [comment]
Merci de fournir plus d'explication car je ne comprends pas bien le problème soulevé.

**Comment by bi-ayefo** [comment]
Quand il y a une erreur lors de l'import, le système indique la ligne de l'erreur.

Avant l'implémentation de la prise en compte du retour à la ligne, lorsque j'avais un erreur lors de l'import, pour pouvoir déterminer la ligne proprement dite, je copie le contenu du textarea dans un éditeur de texte qui affiche les numéros de ligne (par exemple Notepad). Dans l'éditeur je cherche la ligne correspondant au numéro indiqué et je corrige cette ligne pour ne plus avoir l'erreur.

Après l'implémentation de la prise en compte  du retour à la ligne, lorsque le système m'indique le numéro de la ligne, quand je cherche dans Notepad, la ligne en erreur ne correspond pas au numéro de ligne indiqué. Car quand je vais sur le numéro de ligne indiqué, la ligne est correcte. C'est après plusieurs tentatives et tâtonnements que j'arrive à trouver la ligne qui est n'est pas correcte.

Je me suis dit que c'est lié à la nouvelle gestion du retour à la ligne mais peut-être que cela est dû à autre chose.

La prise en compte du issue #23 permettrait de faciliter l'analyse de ce genre de problèmes.

Exemple avec ce jeu de test

18/10/2018;14:45;;Item 1
18/10/2018;14:55;16:05;""Item 2
Item 2 suite
Item 2 suite
Item 2 fin""
18/10/2018;16:55;17:20;Item 3
18/10/2018;17:25;17:55;""Item 4
Item 4 suite
Item 4 suite
Item 4 fin""
18/10/2018;18:10;18:40;""Item 5
Item 5 suite
Item 5 fin""
18/10/2018;18:45;;Item 6
18/10/2018;19:00;20:30;Item 7
18/10/2018;;;Item 8
18/10/2018;;;Item 9
18/10/2018;Item 10 en erreur;;
19/10/2018;05:45;;Item 11
19/10/2018;06:40;;Item 12
19/10/2018;;;Item 13

Il dit qu'il y a erreur à la ligne 10 alors que l'erreur se trouve à la ligne 18

![image](https://user-images.githubusercontent.com/8646786/47978968-7701a180-e0b8-11e8-9995-586ad77c3753.png)

![numero de ligne](https://user-images.githubusercontent.com/8646786/47978975-8385fa00-e0b8-11e8-9c25-24e25befc2df.jpg)

Avec la prise en compte du retour à la ligne, un item ne correspond plus forcément à une ligne. Sinon il serait difficile de trouver et corriger les items en erreur.

**Comment by rodrigueaf** [comment]
Corrigé

**Comment by bi-ayefo** [comment]
Vérifications OK.
