### ISSUE TITLE
Import journal : Erreur non détectée lorsque le champ description est vide

### ISSUE THREAD

**Issue by bi-ayefo** [rodrigueaf/janusgs#26]
![erreur description vide](https://user-images.githubusercontent.com/8646786/47959870-844e5b80-dfe6-11e8-8454-8dcd9f4ab739.jpg)

**Comment by rodrigueaf** [comment]
Quel est l'objectif de mettre des descriptions vides?

**Comment by bi-ayefo** [comment]
Aucun objectif justement. Au lieu de signaler une erreur inconnue (contacter l'administrateur), le système devrait signaler la ligne à laquelle se présente l'erreur comme c'est le cas d'habitude.

**Comment by rodrigueaf** [comment]
Corrigé

**Comment by bi-ayefo** [comment]
Vérifications OK.
