### ISSUE TITLE
Affichage lignes journal / Séparer date de réalisation des heures debut et fin

### ISSUE THREAD

**Issue by bi-ayefo** [rodrigueaf/janusgs#3]
- [ ] Etudier la situation : Actuellement il est possible de commencer une tâche à la date d1 et la terminer à la date d2. Il vaut mieux éviter cela. On va supposer qu'une tâche de la journée d1 est censée se terminer à 23:59 de cette journée. Si la tâche se poursuit jusqu'au lendemain, créer une autre tâche commençant à 00:00 à la date du jour suivant.
- [ ] Appliquer le correctif dans la base de données et sur le frontend. Proposition : Utiliser plutôt les champs daterealisation, heuredebut, heurefin.
- [ ] Mettre à jour les spécifications et les tests

**Comment by bi-ayefo** [comment]
Exemple de conséquence
Les lignes à importer qui n'ont pas de date début ou date fin n'affichent pas les colonnes date début et date fin dans le journal.

La date est bien présente dans la ligne à importer

![probleme colonne date et heure csv](https://user-images.githubusercontent.com/8646786/44344059-30b88100-a47f-11e8-9e64-edf8a4ea1b48.PNG)

Dans la base

![probleme colonne date et heure](https://user-images.githubusercontent.com/8646786/44344060-30b88100-a47f-11e8-853b-09939ef9ed64.PNG)


A l'affichage

![probleme colonne date et heure affichage](https://user-images.githubusercontent.com/8646786/44344062-31511780-a47f-11e8-9ffc-91aca4807aaf.PNG)

**Comment by rodrigueaf** [comment]
Problème résolu
