### ISSUE TITLE
Prévision/Journal : Lenteur lors de la sélection des listes déroulantes

### ISSUE THREAD

**Issue by bi-ayefo** [rodrigueaf/janusgs#6]
Par exemple sélection de la catégorie

![image](https://user-images.githubusercontent.com/8646786/44298436-a6cbb500-a2d2-11e8-98a3-6d6d6248cd22.png)

Etudier la possibilité de vérifier la correction de façon formelle. (par exemple avec des tests de performance - temps de réponse)

**Comment by rodrigueaf** [comment]
Lenteur non observée à mon niveau ni sur la version en ligne ni en local

**Comment by bi-ayefo** [comment]
Je vais préparer des détails complémentaires. Ou alors on peut planifier une rencontre pour que je te montre.

**Comment by bi-ayefo** [comment]
Il y a eu des améliorations considérables avec le datagrid. A mettre en observation.

**Comment by bi-ayefo** [comment]
Résolu avec le nouveau datagrid.
